version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketbridge-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/marketbridge_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - JWT_SECRET=357638792F423F4428472B4B6250655368566D597133743677397A2443264629
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - marketbridge-network
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:17-alpine
    container_name: marketbridge-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=marketbridge_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marketbridge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketbridge_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  marketbridge-network:
